### ISSUE TITLE
the result when dirichlet=0.1

### ISSUE THREAD

**Issue by Bhongcheng** [jinkyu032/FedMLB#2]
It seems that in this setting, FedMLB does not perform much better than FedAvg during early rounds?(for example, rounds<=400). What do you think of this phenomenon?
    Thank you.

**Comment by jinkyu032** [comment]
Hi bhongcheng.
I think this is because we use previous global model as a teacher model.
Although previous global model has global knowledge about whole training data,
it is not matured until sufficient global round.
This is different from centralized training knowledge distillation, where teacher model is train-finished model from the very first epoch of training student model.

It seems like using warming up techniques or finding the way to discriminate whether use distillation from current teacher model is helpful or not will be interesting issue.
Thank you.

**Comment by Bhongcheng** [comment]
Thanks for your warm replay!

**Comment by chenrxi** [comment]
It seems that in the author's setting, the global model is not well trained utils 400 epoch. And the differences on clients' accuracy will occur after 400 epoch.
